# Generated by Django 4.2.23 on 2025-11-19 14:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_profissional', models.TextField(blank=True, help_text='Descreva seus objetivos de carreira e o que você busca', max_length=1000, verbose_name='Objetivo Profissional')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('visivel', models.BooleanField(default=True, verbose_name='Visível para Empresas')),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículos',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Habilidade')),
                ('categoria', models.CharField(choices=[('tecnica', 'Técnica'), ('idioma', 'Idioma'), ('soft', 'Soft Skill'), ('ferramenta', 'Ferramenta')], default='tecnica', max_length=20, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Foto de Perfil')),
                ('bio', models.TextField(blank=True, help_text='Conte um pouco sobre você (máx. 500 caracteres)', max_length=500, verbose_name='Biografia')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, help_text='Ex: SP, RJ, MG', max_length=2, verbose_name='Estado (UF)')),
                ('cep', models.CharField(blank=True, help_text='Formato: 00000-000', max_length=9, verbose_name='CEP')),
                ('area_interesse', models.CharField(blank=True, help_text='Ex: Desenvolvimento Web, Design, Marketing', max_length=200, verbose_name='Área de Interesse')),
                ('nivel_experiencia', models.CharField(choices=[('estagiario', 'Estagiário'), ('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior'), ('sem_experiencia', 'Sem Experiência')], default='sem_experiencia', max_length=20, verbose_name='Nível de Experiência')),
                ('disponibilidade', models.CharField(choices=[('integral', 'Tempo Integral'), ('parcial', 'Meio Período'), ('freelancer', 'Freelancer'), ('estagio', 'Estágio')], default='integral', max_length=20, verbose_name='Disponibilidade')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfólio')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('perfil_completo', models.BooleanField(default=False, help_text='Indica se o perfil tem todas as informações preenchidas', verbose_name='Perfil Completo')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o perfil está ativo e visível para empresas', verbose_name='Ativo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil do Estudante',
                'verbose_name_plural': 'Perfis dos Estudantes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('localizacao', models.CharField(blank=True, help_text='Ex: São Paulo, SP', max_length=200, verbose_name='Localização')),
                ('tipo_emprego', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio'), ('freelance', 'Freelance'), ('autonomo', 'Autônomo')], default='clt', max_length=20, verbose_name='Tipo de Emprego')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Deixe em branco se ainda trabalha aqui', null=True, verbose_name='Data de Término')),
                ('trabalho_atual', models.BooleanField(default=False, verbose_name='Trabalho Atual')),
                ('descricao', models.TextField(blank=True, help_text='Descreva suas principais responsabilidades e conquistas. Seja criativo!', max_length=2000, verbose_name='Descrição das Atividades')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='student_area.resume', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Experiência Profissional',
                'verbose_name_plural': 'Experiências Profissionais',
                'ordering': ['-data_inicio', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='student_area.studentprofile', verbose_name='Estudante'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=50, verbose_name='Idioma')),
                ('nivel_leitura', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('fluente', 'Fluente'), ('nativo', 'Nativo')], max_length=20, verbose_name='Nível de Leitura')),
                ('nivel_escrita', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('fluente', 'Fluente'), ('nativo', 'Nativo')], max_length=20, verbose_name='Nível de Escrita')),
                ('nivel_conversacao', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('fluente', 'Fluente'), ('nativo', 'Nativo')], max_length=20, verbose_name='Nível de Conversação')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='student_area.resume', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['ordem', 'idioma'],
            },
        ),
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Vaga')),
                ('empresa', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('logo_empresa', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo da Empresa')),
                ('descricao', models.TextField(help_text='Descreva as responsabilidades e atividades do cargo', verbose_name='Descrição da Vaga')),
                ('requisitos', models.TextField(help_text='Liste os requisitos obrigatórios para a vaga', verbose_name='Requisitos')),
                ('requisitos_desejaveis', models.TextField(blank=True, help_text='Liste os requisitos opcionais/desejáveis', verbose_name='Requisitos Desejáveis')),
                ('beneficios', models.TextField(blank=True, help_text='Liste os benefícios oferecidos pela empresa', verbose_name='Benefícios')),
                ('tipo_vaga', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio'), ('freelance', 'Freelance'), ('temporario', 'Temporário')], max_length=20, verbose_name='Tipo de Contratação')),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20, verbose_name='Modalidade de Trabalho')),
                ('jornada', models.CharField(choices=[('integral', 'Tempo Integral'), ('parcial', 'Meio Período'), ('flexivel', 'Flexível')], default='integral', max_length=20, verbose_name='Jornada de Trabalho')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('endereco_completo', models.CharField(blank=True, max_length=300, verbose_name='Endereço Completo')),
                ('faixa_salarial_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Mínimo')),
                ('faixa_salarial_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Máximo')),
                ('salario_a_combinar', models.BooleanField(default=False, verbose_name='Salário a Combinar')),
                ('nivel_experiencia', models.CharField(choices=[('estagiario', 'Estagiário'), ('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior'), ('sem_experiencia', 'Sem Experiência')], max_length=20, verbose_name='Nível de Experiência Requerido')),
                ('area_atuacao', models.CharField(help_text='Ex: Tecnologia, Marketing, Design, etc.', max_length=100, verbose_name='Área de Atuação')),
                ('categoria', models.CharField(blank=True, help_text='Ex: Desenvolvimento Web, UX/UI, Marketing Digital', max_length=100, verbose_name='Categoria')),
                ('numero_vagas', models.IntegerField(default=1, verbose_name='Número de Vagas Disponíveis')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='Email para Contato')),
                ('telefone_contato', models.CharField(blank=True, max_length=17, verbose_name='Telefone para Contato')),
                ('site_empresa', models.URLField(blank=True, max_length=300, verbose_name='Site da Empresa')),
                ('url_aplicacao_externa', models.URLField(blank=True, help_text='Link externo para aplicação (se houver)', max_length=500, verbose_name='URL de Candidatura Externa')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('encerrada', 'Encerrada'), ('preenchida', 'Preenchida')], default='ativa', max_length=20, verbose_name='Status da Vaga')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('data_expiracao', models.DateField(blank=True, help_text='Data limite para candidaturas', null=True, verbose_name='Data de Expiração')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('destaque', models.BooleanField(default=False, help_text='Vagas em destaque aparecem no topo das listagens', verbose_name='Vaga em Destaque')),
                ('urgente', models.BooleanField(default=False, verbose_name='Vaga Urgente')),
                ('visualizacoes', models.IntegerField(default=0, verbose_name='Número de Visualizações')),
                ('numero_candidaturas', models.IntegerField(default=0, verbose_name='Número de Candidaturas')),
                ('habilidades_requeridas', models.ManyToManyField(blank=True, related_name='vagas', to='student_area.skill', verbose_name='Habilidades Requeridas')),
                ('publicado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_publicadas', to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
            ],
            options={
                'verbose_name': 'Vaga de Emprego',
                'verbose_name_plural': 'Vagas de Emprego',
                'ordering': ['-destaque', '-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta_motivacao', models.TextField(blank=True, help_text='Explique por que você é o candidato ideal para esta vaga', max_length=2000, verbose_name='Carta de Motivação')),
                ('curriculo_anexado', models.FileField(blank=True, help_text='Anexe seu currículo em PDF', null=True, upload_to='applications/resumes/', verbose_name='Currículo Anexado (PDF)')),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('em_analise', 'Em Análise'), ('pre_selecionado', 'Pré-selecionado'), ('entrevista', 'Entrevista Agendada'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelada', 'Cancelada')], default='enviada', max_length=20, verbose_name='Status')),
                ('data_candidatura', models.DateTimeField(auto_now_add=True, verbose_name='Data da Candidatura')),
                ('data_atualizacao_status', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('feedback_empresa', models.TextField(blank=True, verbose_name='Feedback da Empresa')),
                ('visualizada_empresa', models.BooleanField(default=False, verbose_name='Visualizada pela Empresa')),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Visualização')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='student_area.studentprofile', verbose_name='Estudante')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='student_area.jobopportunity', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['-data_candidatura'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=200, verbose_name='Instituição de Ensino')),
                ('curso', models.CharField(max_length=200, verbose_name='Curso/Formação')),
                ('nivel', models.CharField(choices=[('medio', 'Ensino Médio'), ('tecnico', 'Técnico'), ('graduacao', 'Graduação'), ('pos', 'Pós-Graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=20, verbose_name='Nível de Formação')),
                ('status', models.CharField(choices=[('cursando', 'Cursando'), ('concluido', 'Concluído'), ('trancado', 'Trancado'), ('incompleto', 'Incompleto')], default='cursando', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão/Previsão')),
                ('descricao', models.TextField(blank=True, help_text='Principais disciplinas, projetos ou conquistas', max_length=1000, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacoes', to='student_area.resume', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Formação Acadêmica',
                'verbose_name_plural': 'Formações Acadêmicas',
                'ordering': ['-data_inicio', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Certificação/Curso')),
                ('instituicao', models.CharField(max_length=200, verbose_name='Instituição Emissora')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_validade', models.DateField(blank=True, help_text='Deixe em branco se não expira', null=True, verbose_name='Data de Validade')),
                ('codigo_credencial', models.CharField(blank=True, max_length=200, verbose_name='Código/ID da Credencial')),
                ('url_credencial', models.URLField(blank=True, help_text='Link para verificação da certificação', max_length=500, verbose_name='URL da Credencial')),
                ('descricao', models.TextField(blank=True, max_length=1000, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificacoes', to='student_area.resume', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
                'ordering': ['-data_emissao', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('expert', 'Expert')], default='intermediario', max_length=20, verbose_name='Nível de Proficiência')),
                ('anos_experiencia', models.IntegerField(blank=True, null=True, verbose_name='Anos de Experiência')),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudantes', to='student_area.skill', verbose_name='Habilidade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='student_area.studentprofile', verbose_name='Estudante')),
            ],
            options={
                'verbose_name': 'Habilidade do Estudante',
                'verbose_name_plural': 'Habilidades dos Estudantes',
                'ordering': ['-nivel', 'skill__nome'],
                'unique_together': {('student', 'skill')},
            },
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['-data_publicacao'], name='student_are_data_pu_c372f4_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['status', '-data_publicacao'], name='student_are_status_e93fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['area_atuacao', 'status'], name='student_are_area_at_1a098b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['student', '-data_candidatura'], name='student_are_student_e486c3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['vaga', 'status'], name='student_are_vaga_id_992fe9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('student', 'vaga')},
        ),
    ]
