# Generated by Django 4.2.23 on 2025-11-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do usuário (único)', max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
    ]
