"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-f#5bkmhy3dof3eky_x((yn+ia(!qtc-7kc9ky-1yw5ti6o$*nc"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "corsheaders",  # Adicionado para CORS
    "config.apps.ConfigConfig",  # Config app with custom admin configuration
    "users",  # Atualizado de "cadastro" para "users"
    "career",  # Novo app para trilhas de carreira
    "llm",  # LLM integration (Gemini API)
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "student_area",  # Área do estudante
    "rest_framework",  # Django REST Framework
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Security headers configuration
# Note: The Permissions Policy violation warning for 'unload' in RelatedObjectLookups.js
# is a known Django Admin issue and can be safely ignored in development.
# It doesn't affect functionality - Django Admin popups still work correctly.
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'SAMEORIGIN'  # Allows Django Admin popups/iframes to work

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Django Admin uses its own templates
        # Frontend React handles all user-facing UI
        "DIRS": [],
        "APP_DIRS": True,  # Enables Django to find templates in app directories (for Django Admin)
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

CORS_ALLOW_ALL_ORIGINS = True  # Temporário para desenvolvimento
CORS_ALLOW_CREDENTIALS = True  # Permite o envio de credenciais (cookies, headers de autorização)
# CORS_ALLOWED_ORIGINS = [
#    "http://localhost:5173",  # Porta padrão do Vite para o frontend
#    "http://127.0.0.1:5173", # Porta padrão do Vite para o frontend
# ]

STATIC_ROOT = BASE_DIR / "staticfiles"  # Para o build de produção

STATICFILES_DIRS = [
    # BASE_DIR / "users" / "static",  # Removido - pasta não existe mais
    BASE_DIR.parent / "frontend" / "dist",  # Frontend build directory
]

# Authentication
# Django Admin uses its own login at /admin/login/
# Custom app login is at /login/ (for frontend React)
LOGIN_URL = "/admin/login/"  # Django Admin login (porta 8000)
LOGIN_REDIRECT_URL = "/student/"  # Redirect after login for regular users
ADMIN_LOGIN_REDIRECT_URL = "/admin/"  # Redirect after admin login

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Django Admin Configuration
# Customize admin site header and title
ADMIN_SITE_HEADER = "JobPathAI - Administração"
ADMIN_SITE_TITLE = "JobPathAI Admin"
ADMIN_INDEX_TITLE = "Painel de Administração"
