# Generated by Django 4.2.23 on 2025-11-23 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='career.careerstage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stage Progress',
                'verbose_name_plural': 'User Stage Progresses',
                'ordering': ['stage__order'],
                'unique_together': {('user', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='UserCareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether user is actively following this path')),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_associations', to='career.careerpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_career_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Career Path Association',
                'verbose_name_plural': 'User Career Path Associations',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'career_path')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='career.careerpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'career_path')},
            },
        ),
    ]
