# Generated by Django 4.2.23 on 2025-11-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_userstageprogress_usercareerpath_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerpath',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='careerpath',
            name='area',
            field=models.CharField(blank=True, choices=[('Tecnologia', 'Tecnologia'), ('Design', 'Design'), ('Negócios', 'Negócios'), ('Dados', 'Dados'), ('Marketing', 'Marketing'), ('Vendas', 'Vendas'), ('Recursos Humanos', 'Recursos Humanos'), ('Finanças', 'Finanças'), ('Outras', 'Outras')], help_text='Área profissional da trilha', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='estimated_time_months',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo estimado em meses', null=True),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='hours_per_week',
            field=models.PositiveIntegerField(blank=True, help_text='Horas de estudo por semana', null=True),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se a trilha está ativa e disponível para usuários'),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='level',
            field=models.CharField(blank=True, choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado'), ('Iniciante a Intermediário', 'Iniciante a Intermediário'), ('Intermediário a Avançado', 'Intermediário a Avançado')], help_text='Nível de dificuldade', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='careerpath',
            index=models.Index(fields=['area'], name='career_care_area_acb44b_idx'),
        ),
        migrations.AddIndex(
            model_name='careerpath',
            index=models.Index(fields=['level'], name='career_care_level_013209_idx'),
        ),
        migrations.AddIndex(
            model_name='careerpath',
            index=models.Index(fields=['is_active'], name='career_care_is_acti_598e41_idx'),
        ),
    ]
