# Generated by Django 4.2.23 on 2025-11-23 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_add_career_path_metadata_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da área profissional', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição da área profissional', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se a área está ativa e disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área Profissional',
                'verbose_name_plural': 'Áreas Profissionais',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='careerpath',
            new_name='career_care_area_id_b938f5_idx',
            old_name='career_care_area_acb44b_idx',
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Área profissional da trilha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_paths', to='career.area'),
        ),
    ]
