# Generated by Django 4.2.23 on 2025-11-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_migrate_area_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('declined', 'Recusada')], default='pending', max_length=20),
        ),
    ]
