# Generated by Django 5.2.6 on 2025-09-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('idade', models.PositiveBigIntegerField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
